apiVersion: v2
name: openg2p-g2p-bridge-example-bank-celery
description: A Helm chart for OpenG2P G2P Bridge Example Bank Celery
type: application
version: 1.0.0
appVersion: ""
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 15.x.x
  condition: postgresql.enabled
- name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 20.x.x
  condition: redis.enabled
keywords:
  - bridge-bank-celery
maintainers:
  - email: info@openg2p.org
    name: OpenG2P
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "OpenG2P-G2P-Bridge-Example-Bank-Celery"
