openg2p-g2p-bridge-example-bank-api:
  enabled: true
  common:
    enabled: false
  postgresql:
    enabled: false
  envVars:
    EXAMPLE_BANK_DB_HOSTNAME: '{{ .Release.Name }}-postgresql'
    EXAMPLE_BANK_DB_DBNAME: example_bank_db
    EXAMPLE_BANK_DB_USERNAME: bankuser
    EXAMPLE_BANK_CELERY_BROKER_URL: redis://{{ .Release.Name }}-redis-master:6379/0
    EXAMPLE_BANK_CELERY_BACKEND_URL: redis://{{ .Release.Name }}-redis-master:6379/0

  envVarsFrom:
    EXAMPLE_BANK_DB_PASSWORD:
      secretKeyRef:
        name: '{{ .Release.Name }}-postgresql'
        key: password

openg2p-g2p-bridge-example-bank-celery:
  enabled: true
  common:
    enabled: false
  postgresql:
    enabled: false
  redis:
    enabled: false
  envVars:
    EXAMPLE_BANK_CELERY_DB_HOSTNAME: '{{ .Release.Name }}-postgresql'
    EXAMPLE_BANK_CELERY_DB_DBNAME: example_bank_db
    EXAMPLE_BANK_CELERY_DB_USERNAME: bankuser
    EXAMPLE_BANK_CELERY_CELERY_BROKER_URL: redis://{{ .Release.Name }}-redis-master:6379/0
    EXAMPLE_BANK_CELERY_CELERY_BACKEND_URL: redis://{{ .Release.Name }}-redis-master:6379/0

  envVarsFrom:
    EXAMPLE_BANK_CELERY_DB_PASSWORD:
      secretKeyRef:
        name: '{{ .Release.Name }}-postgresql'
        key: password

postgresql:
  enabled: true
  auth:
    username: bankuser
    database: example_bank_db
  primary:
    extendedConfiguration: |-
      wal_level = logical
      max_wal_senders = 20
      max_replication_slots = 10

redis:
  cluster:
    enabled: false
  replicaCount: 1
  auth:
    enabled: false
